apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomswebapp
  name: tomswebapp
  namespace: default
spec:
  ports:
  - nodePort: 30400
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tomswebapp
  type: NodePort
